#!/usr/bin/env python3
"""Post-approval finish for divsub: local-check → live upload → invocations →
buildPackage → link. Artifacts already generated by the subagents.
"""
import os, sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))


def load_dotenv(path):
    sec = {"POLYGON_API_KEY", "POLYGON_API_SECRET"}
    for line in Path(path).read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, _, v = line.partition("="); k = k.strip()
            os.environ.setdefault(k, v.strip() if k in sec else v.split("#", 1)[0].strip())


load_dotenv(REPO / ".env")

from orchestrator import (Orchestrator, PolygonUploader, parse_create_problem,
                          StateStore, PipelineHalt)
from polygon_client.auth import PolygonSession

ci = parse_create_problem(Path("/tmp/divsub_input.txt").read_text())
orch = Orchestrator(problems_root=REPO / "problems",
                    runner=lambda *a, **k: "noop",
                    uploader=PolygonUploader(PolygonSession.from_env()),
                    create_input=ci)

print("→ local self-check (re-run via orchestrator, sets verdict matrix for tags)")
report = orch.local_check()
print("  " + report.text().splitlines()[0])
if not report.ok:
    print(report.text()); sys.exit(1)

print("→ upload (REAL Polygon, tab-by-tab, incl. validator tests)")
created = orch.upload()
print(f"  created id={created['id']} owner={created['owner']}")

print("→ invocations (local harness) + classification")
orch.run_invocations()

print("→ finalize (REAL buildPackage — may take ~1-2 min)")
try:
    result = orch.finalize(created)
except PipelineHalt as e:
    print(f"  HALT: {e}")
    from polygon_client import methods as m
    pkgs = m.packages(PolygonSession.from_env(), created["id"]) or []
    for p in pkgs:
        print(f"  package {p.get('id')}: {p.get('state')} — {p.get('comment','')}")
    sys.exit(2)

print("\n" + result)
print(f"\n(problem id {created['id']}, state {StateStore.load(orch.problem_dir).state.value})")
