"""Local judge: run every solution against every test through the real checker,
producing a verdict matrix (§10, §15).

Reference answers are generated by the main solution. The checker is the actual
testlib standard checker (vendored) or the problem's custom checker.cpp — so
local verdicts match Polygon semantics as closely as a local run can (modulo
compiler/machine differences, which is the known weakness of local-only
verification, §9.4).

Verdicts: AC, WA, TL, RE.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from ._exec import compile_cpp, run, solution_cmd, warmup, VENDOR
from .problem import Problem
from .materialize import materialize, MaterializedTest


@dataclass
class JudgeResult:
    ok: bool
    matrix: dict[str, dict[int, str]] = field(default_factory=dict)
    report: str = ""


def _runnable(sol: Path, build_dir: Path) -> list[str]:
    cmd, cpp = solution_cmd(sol, build_dir)
    if cpp is not None:
        res = compile_cpp(cpp, build_dir / cpp.stem, warnings_as_errors=False)
        if not res.ok:
            raise RuntimeError(f"failed to compile {sol.name}: {res.stderr[:300]}")
    return cmd


def _checker_binary(p: Problem) -> Path:
    build = p.build_dir
    if p.is_standard_checker():
        src = VENDOR / "checkers" / f"{p.standard_checker_stem()}.cpp"
        out = build / f"checker_{p.standard_checker_stem()}"
    else:
        src = p.dir / p.checker["custom"]  # type: ignore
        out = build / "checker_custom"
    res = compile_cpp(src, out, warnings_as_errors=False)
    if not res.ok:
        raise RuntimeError(f"failed to compile checker {src.name}: {res.stderr[:300]}")
    return out


def judge(problem_dir: Path, tests: list[MaterializedTest] | None = None) -> JudgeResult:
    p = Problem.load(problem_dir)
    if tests is None:
        ok, tests, mlog = materialize(problem_dir)
        if not ok:
            return JudgeResult(ok=False, report=mlog)

    checker = _checker_binary(p)

    # 1. reference answers from the main solution
    main_path = p.solutions_dir / p.main_solution
    main_cmd = _runnable(main_path, p.build_dir)
    warmup(main_cmd)
    answers: dict[int, Path] = {}
    for t in tests:
        res = run(main_cmd, stdin_path=t.path, timeout_ms=max(p.time_limit_ms * 5, 5000))
        if res.exit_code != 0:
            return JudgeResult(ok=False,
                               report=f"main solution {p.main_solution} failed on test {t.index}")
        ans = p.build_dir / f"ans_{t.index:03d}"
        ans.write_text(res.stdout)
        answers[t.index] = ans

    # 2. judge every solution
    matrix: dict[str, dict[int, str]] = {}
    for sol in p.solution_files():
        cmd = _runnable(sol, p.build_dir)
        warmup(cmd)
        row: dict[int, str] = {}
        for t in tests:
            res = run(cmd, stdin_path=t.path, timeout_ms=p.time_limit_ms)
            if res.timed_out:
                row[t.index] = "TL"
                continue
            if res.exit_code != 0:
                row[t.index] = "RE"
                continue
            out_file = p.build_dir / f"out_{sol.stem}_{t.index:03d}"
            out_file.write_text(res.stdout)
            chk = run([str(checker), str(t.path), str(out_file), str(answers[t.index])])
            row[t.index] = "AC" if chk.exit_code == 0 else "WA"
        matrix[sol.name] = row

    return JudgeResult(ok=True, matrix=matrix, report=_format(matrix, tests))


def _format(matrix: dict[str, dict[int, str]], tests: list[MaterializedTest]) -> str:
    idxs = [t.index for t in tests]
    lines = ["verdict matrix (rows=solutions, cols=tests):"]
    width = max((len(s) for s in matrix), default=8)
    lines.append("  " + " " * width + "  " + " ".join(f"{i:>3}" for i in idxs))
    for sol, row in matrix.items():
        cells = " ".join(f"{row.get(i,'-'):>3}" for i in idxs)
        lines.append(f"  {sol:<{width}}  {cells}")
    return "\n".join(lines)
